repos:
  # general formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: forbid-tabs

  # formatting mainly for web/config files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  # sorts python imports alphabetically
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [text]
        types_or: [python, cython]
        args: ["--profile", "black"]

  # python linting
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  # formats python code
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black

  # checks python typing
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy

  # docker linter
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  # GitHub actions linter
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.17.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck

  # ansible linter
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.3.0
    hooks:
      - id: ansible-lint
